Repository soyeon1806/AlgoDuo, pull requests merged in 2024-11, with the labels that each got.

#2 [241106] README 및 PR 템플릿 업데이트 - 소연
  .github/PULL_REQUEST_TEMPLAGE.md
  README.md
Labels: Review 요청

#11 [241106] PGS 카펫 - 소연
  README.md
  soyeon/PGS/카펫.java
Labels: Review 요청, 완전 탐색

#13 [241106] PGS 카펫 - 윤교
  soyeon/PGS/카펫.java
  yoonkyo/PGS/카펫.py
Labels: Review 요청, 완전 탐색

#15 [241106] PGS 카펫 - 소연
  soyeon/PGS/카펫.java
Labels: 완전 탐색

#19 [241107] PGS 두 원 사이의 정수 쌍 - 윤교
  yoonkyo/PGS/같은숫자는싫어.py
  yoonkyo/PGS/두원사이의정수쌍.py
Labels: Review 요청, 수학

#20 [241107] PGS 같은 숫자는 싫어 - 소연
  soyeon/PGS/같은_숫자는_싫어.java
  soyeon/PGS/카펫.java
Labels: Review 요청

#21 [241107] PGS 두 원 사이의 정수 쌍 - 소연
  soyeon/PGS/두_원_사이의_정수_쌍.java
Labels: Review 요청, 수학

#26 [241110] PGS 짝지어 제거하기 - 소연
  soyeon/PGS/짝지어_제거하기.java
Labels: Review 요청, 스택 / 큐

#28 [241113] PGS 최댓값과 최솟값 - 윤교
  yoonkyo/PGS/최댓값과최솟값.py
Labels: Review 요청

#29 [241113] PGS 짝지어 제거하기 - 윤교
  yoonkyo/PGS/짝지어_제거하기.py
Labels: 스택 / 큐

#30 [241118] PGS 공원 산책 - 소연
  soyeon/PGS/공원_산책.java
Labels: Review 요청

#31 [241118] PGS_공원_산책 - 윤교
  yoonkyo/PGS/공원_산책.py
Labels: Review 요청

#33 [241119] ETC 구름공원 - 소연
  soyeon/ETC/구름공원.java
Labels: Review 요청
